config/routes.rb
Rails.application.routes.draw do
  resources :harfiles do
    resources 'requests'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/harfile.rb
class Harfile < ApplicationRecord
  validates_with HarValidator

  def json_contents
    JSON.parse(contents)
  end

  def pretty_contents
    JSON.pretty_generate(json_contents)
  end

  def requests
    json_contents
      .dig('log', 'entries')
      .collect do |entry|
        entry
          .dig('request')
          .slice('method', 'url')
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/harfiles_controller.rb
class HarfilesController < ApplicationController
  before_action :set_harfile, only: [:show, :edit, :update, :destroy]

  # GET /harfiles
  # GET /harfiles.json
  def index
    @harfiles = Harfile.all
  end

  # GET /harfiles/1
  # GET /harfiles/1.json
  def show
  end

  # GET /harfiles/new
  def new
    @harfile = Harfile.new
  end

  # GET /harfiles/1/edit
  def edit
  end

  # POST /harfiles
  # POST /harfiles.json
  def create
    @harfile = Harfile.new(harfile_params)

    respond_to do |format|
      if @harfile.save
        format.html { redirect_to @harfile, notice: 'Harfile was successfully created.' }
        format.json { render :show, status: :created, location: @harfile }
      else
        format.html { render :new }
        format.json { render json: @harfile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /harfiles/1
  # PATCH/PUT /harfiles/1.json
  def update
    respond_to do |format|
      if @harfile.update(harfile_params)
        format.html { redirect_to @harfile, notice: 'Harfile was successfully updated.' }
        format.json { render :show, status: :ok, location: @harfile }
      else
        format.html { render :edit }
        format.json { render json: @harfile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /harfiles/1
  # DELETE /harfiles/1.json
  def destroy
    @harfile.destroy
    respond_to do |format|
      format.html { redirect_to harfiles_url, notice: 'Harfile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_harfile
      @harfile = Harfile.find(params[:id])
    end

    def harfile_params
      params.require(:harfile).permit(:name).merge(
        contents: utf8_data
      )
    end

    def content_tempfile
      params['harfile']['contents'].try(:tempfile)
    end

    def utf8_data
      return nil if content_tempfile.blank?
      # return content_tempfile.read # this way fails
      File.open(content_tempfile.path, 'r:UTF-8', &:read)
    end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  def index
    @harfile = Harfile.find params['harfile_id']
    @requests = @harfile.requests
    render json: { requests: @requests }
  end

  def show
    @harfile = Harfile.find params['harfile_id']
    @requests = @harfile.requests
    @request = @requests[params['id'].to_i]
    render json: { request: @request }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/harfiles_helper.rb
module HarfilesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/harfiles/_form.html.erb
<%= form_for(harfile) do |f| %>
  <% if harfile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(harfile.errors.count, "error") %> prohibited this harfile from being saved:</h2>

      <ul>
      <% harfile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :contents, "HAR File" %>
    <%= f.file_field :contents %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/harfiles/edit.html.erb
<h1>Editing Harfile</h1>

<%= render 'form', harfile: @harfile %>

<%= link_to 'Show', @harfile %> |
<%= link_to 'Back', harfiles_path %>

app/views/harfiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Harfiles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @harfiles.each do |harfile| %>
      <tr>
        <td><%= harfile.name %></td>
        <td><%= link_to 'Show', harfile %></td>
        <td><%= link_to 'Edit', edit_harfile_path(harfile) %></td>
        <td><%= link_to 'Destroy', harfile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Harfile', new_harfile_path %>

app/views/harfiles/new.html.erb
<h1>New Harfile</h1>

<%= render 'form', harfile: @harfile %>

<%= link_to 'Back', harfiles_path %>

app/views/harfiles/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_harfile_path(@harfile) %> |
<%= link_to 'Back', harfiles_path %>

<p>
  <strong>Name:</strong>
  <%= @harfile.name %>
</p>
<p>
  <strong>Contents:</strong>
  <pre>
    <%= @harfile.pretty_contents %>
  </pre>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HarManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>